# language: php

checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        code_rating: true
        duplication: true

tools:
    sensiolabs_security_checker: true
    external_code_coverage: false
